package com.example.moneymanager.api

import com.example.moneymanager.database.LocalAccount
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class AccountHelper {

    suspend fun setupAndFetchAccounts(api: AccountApi, userGuid: String): List<LocalAccount> {
        return withContext(Dispatchers.IO) {
            try {
                // Fetch accounts from the API
                val accountsResponse = api.fetchAccounts(userGuid)

                // Map the response to LocalAccount list
                accountsResponse.accounts.map {
                    LocalAccount(
                        id = 0,  // ID will be auto-generated by the database
                        guid = it.guid,
                        type = it.type ?: "Unknown",
                        name = it.name,
                        balance = it.balance
                    )
                }
            } catch (e: Exception) {
                e.printStackTrace()
                emptyList() // Return an empty list in case of failure
            }
        }
    }
}
